title: Docker notes
description: Notes from installation process of powershell and docker on win 2016

url: mateuszmik.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: mateuszmik
   twitter: mateuszmik

google_analytics: "UA-110604186-1"
